apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastapi-server.fullname" . }}-secret
  labels:
    {{- include "fastapi-server.labels" . | nindent 4 }}
data:
  {{ $mongoDBConnectionURL := printf "mongodb+srv://%s:%s@mongodb-svc.mongodb.svc.cluster.local/college?replicaSet=mongodb&ssl=false" .Values.mongodb.user .Values.mongodb.password | b64enc }}
  MONGODB_URL: {{ $mongoDBConnectionURL }}
  {{ $mongoDBAdminConnectionURL := printf "mongodb+srv://%s:%s@mongodb-svc.mongodb.svc.cluster.local/admin?replicaSet=mongodb&ssl=false" .Values.mongodb.adminUser .Values.mongodb.password | b64enc }}
  MONGODB_ADMIN_URL: {{ $mongoDBAdminConnectionURL }}
