{{- if and .Values.metrics.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "fastapi-server.fullname"  . }}
  labels:
    {{- include "fastapi-server.labels" . | nindent 4 }}
    release: prometheus
spec:
  endpoints:
  - port: {{ .Values.metrics.svc.name }}
  selector:
    matchLabels:
      {{- include "fastapi-server.selectorLabels" . | nindent 6 }}
{{- end }}
