groups:
- name: app_alerts
  rules:
  - alert: HighRequestRate
    expr: rate(server_requests_total[1m]) > 10
    for: 30s
    labels:
      severity: high
    annotations:
      summary: "High request rate detected"
      description: "The app is receiving more than 10 requests per minute"

  - alert: ApplicationDown
    expr: up{job="fastapi-monitoring-app"} == 0
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "Application is down"
      description: "The application is not responding"